- hosts: all
  name: Ansible Tower Apache deployment
  become: true
  become_method: sudo
  become_user: root

  tasks:
  - name: install Apache
    yum:
      name: httpd
      state: latest
  - name: enable Apache
    service:
      name: httpd
      enabled: true
      state: started
  - name: hello world
    copy:
      dest: /var/www/html/index.html
      content: "Hello World G2 en force"
