- hosts: all
  name: installation du server apache et de la base de données
  become: true
  become_method: sudo
  become_user: root

  tasks:
  - name: install apache, php and php-mysql
    yum:
      name: httpd, php, php-mysql, libselinux-python, libsemanage-python, mod_ssl
      state: latest
    when: inventory_hostname in groups.webserver
  - name: config selinux pour http network connect db
    seboolean:
      name: httpd_can_network_connect
      state: yes
      persistent: yes
    when: inventory_hostname in groups.webserver  
  - name: enable apache
    service:
      name: httpd
      enabled: true
      state: restarted
    when: inventory_hostname in groups.webserver  
  - name: place index.php
    get_url:
      dest: /var/www/html/index.php
      url: http://instructor.classroom.local/content/index.php
    when: inventory_hostname in groups.webserver
  - name: config firewall
    firewalld:
      service: '{{ item }}'
      permanent: true
      immediate: true
      state: enabled
    with_items: ['http','https']

  - name: install mariadb-server et mysql-python
    yum:
      name: '{{ item }}'
      state: latest
    with_items: ['mariadb-server','MySQL-python']
    when: inventory_hostname in groups.database
  - name: start and enable mariadb
    service:
      name: mariadb
      enabled: true
      state: started
    when: inventory_hostname in groups.database
  - name: config firewall pour mysql
    firewalld:
      service: mysql
      permanent: true
      immediate: true
      state: enabled
    when: inventory_hostname in groups.database
  - name: config user mysql
    mysql_user:
      name: devops
      password: redhat
      state: present
      host: '%'
    when: inventory_hostname in groups.database
    notify: 
    - restart mariadb

  handlers:
  - name: restart mariadb
    service: name=mariadb state=restarted
