---
- name: Challenge4 webserver
  hosts: webserver
  tasks:
    - name: install http
      become: true
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - httpd
        - mod_ssl
        - php
        - php-mysql
    - name: activation firewall
      firewalld:
        name: "{{ item }}"
        state: enabled
        permanent: true
      with_items:
        - http
        - https
    - name: demarrage service
      become: true
      service:
        name: httpd
        state: started
        enabled: true
    - name: lecture du fichier php
      become: true
      file:
        src: files/index.php
        dest: /var/www/html/
        owner: root
        group: root

- name: Challenge4 mariadb
  hosts: mariadb
  tasks:
    - name: install mariadb
      become: true
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - mariadb-server
        - mariadb-client
    - name: activation des firewall
      firewalld:
        name: mysql
        state: enabled
        permanent: true
    - name: activation service
      service:
        name: mariadb
        state: started
        enabled: true
    - name: creation user
      mysql_user:
        name: 'devops'
        password: 'redhat'
        host_all: yes
...
