- name: install packages on webserver
  hosts: manage_host_1.lab.com
  tasks:
    - name: install packages
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - httpd
        - mod_ssl
        - php
        - php-mysql
    - name: start services
      service:
        name: "{{ item }}"
        state: started
        enabled: true
      with_items:
        - httpd
    - name: open flows
      firewalld:
        service: "{{ item }}"
        permanent: true
        state: enabled
      with_items:
        - http
        - https
- name: install mariadb and start
  hosts: manage_host_2.lab.com
  tasks:
    - name: install mariadb
      yum:
        name: mariadb-server
        state: latest
    - name: start mariadb
      service:
        name: mariadb
        state: started
        enabled: true
