- name: install packages on webserver
  hosts: manage_host_1.lab.com
  tasks:
    - name: install packages
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - httpd
        - mod_ssl
        - php
        - php-mysql
        - MySQL-python
    - name: start services
      service:
        name: "{{ item }}"
        state: started
        enabled: true
      with_items:
        - httpd
    - name: open flows
      firewalld:
        service: "{{ item }}"
        permanent: true
        immediate: true
        state: enabled
      with_items:
        - http
        - https
    - name: copy index.php file
      get_url:
        url : http://instructor.classroom.local/content/index.php
        dest: /var/www/html/index.php
        mode: 0755
- name: install mariadb and start
  hosts: manage_host_2.lab.com
  tasks:
    - name: install mariadb
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - mariadb-server
        - MySQL-python
    - name: start mariadb
      service:
        name: mariadb
        state: started
        enabled: true
    - name: add devops user
      mysql_user:
        name: devops
        password: redhat
#        host: '%'
        host: 192.168.56.11
    - name: open flows
      firewalld:
        service: "{{ item }}"
        permanent: true
        immediate: true
        state: enabled
      with_items:
        - mysql

